---

- name: "Ensure we have a lxd group in the inventory"
  become: yes
  lineinfile: path="{{ inventory_file }}" line="[lxd]"
  delegate_to: localhost

- include_tasks: containers-inner.yml
  with_items: "{{ lxd_containers }}"


