---

# This task installs lxd locally (on the machine you run ansible from).
# This is needed in order to allow ansible to use ansible's lxd connector
# that enables to manage containers on remote hosts. See:
#
# `lxc remote list`

- name: Ensure to have packaged lxd purged on localhost
  apt:
    name: "{{ item }}"
    purge: yes
    state: absent
  with_items:
    - lxd
    - lxd-client
  become: true
  delegate_to: localhost

- name: Ensure lxd snap is installed on localhost
  command: "snap install lxd"
  become: true
  delegate_to: localhost

- name: Ensure local lxd has required lxc remote configured
  expect:
    command: "lxc remote add {{ lxd_init_clust_name }} https://{{ lxd_init_https_addr }}:{{ lxd_init_https_port }} --protocol=lxd --password={{ lxd_init_trust_pass }}"
    responses:
      ok: y
  become: true
  delegate_to: localhost
  register: out
  failed_when: out.stdout is not search('exists')
  ignore_errors: True
  # This one's really fun. We need
  # - the expect to reply "y" when adding a new remote
  # - to fail when the registeredout.stdout doesn't contain the substring "exists",
  #   because adding an already existing remote emits an error

