---

# Use `containername.lxd`-style hostnames for container<->ip resolution.
# Needed if you want this to work:
#
# lxc launch c1 ubuntu:18.04
# ping c1.lxd
#
# The gist is to add the gateway ip of the lxdfan0 interface to lxd host's
# nameservers for all ns requests on the ip range assigned to the lxdfan0.
# The idea comes from: https://blog.simos.info/how-to-use-lxd-container-hostnames-on-the-host-in-ubuntu-18-04/
#
# KNOWN ISSUES:
# Ubuntu's default systemd-resolved doesn't play nice with the dnsmasq used
# by the lxd snap. As a result, after reboot, lxd will start properly after
# a 600s timeout of god knows what. See https://github.com/lxc/lxd/issues/4631
# for a more detailed description.

- name: "Ensure that the lxdhostdns_start script is in place"
  template:
    src: lxdhostdns_start.sh.j2
    dest: /usr/local/bin/lxdhostdns_start.sh
    owner: root
    group: root
    mode: 0755

- name: "Ensure that the lxdhostdns_start stop is in place"
  template:
    src: lxdhostdns_stop.sh.j2
    dest: /usr/local/bin/lxdhostdns_stop.sh
    owner: root
    group: root
    mode: 0755

- name: "Ensure that we have the /etc/systemd/system/snap.lxd.daemon.service.d directory"
  file: 
    path: /etc/systemd/system/snap.lxd.daemon.service.d
    state: directory

- name: "Ensure that snap.lxd.daemon.service unit modifications are installed"
  template:
    src: snap.lxd.service-mage.j2
    dest: /etc/systemd/system/snap.lxd.daemon.service.d/mage.conf
    owner: root
    group: root
    mode: 0644

