---


- name: "Upload temporary yaml config"
  template:
    src: lxd-init.yaml.j2
    dest: /root/mage-lxd-init.yaml.tmp
    owner: root
    group: root
    mode: 0400

- name: Ensure lxd is configured
  shell: "cat /root/mage-lxd-init.yaml.tmp | /snap/bin/lxd init --preseed"
  when: "('error: no matching snaps installed' in snap_list.stderr) or (lxd_init_run == true)"

- pause:
    seconds: 1

- file:
    path: /root/mage-lxd-init.yaml.tmp
    state: absent
